### ISSUE TITLE
Unable to locate the Wakatime menu in services

### ISSUE THREAD

**Issue by Keelan-Matthews** [vanBassum/Wakatime.Unity#17]
I managed to add the package to Unity, but could not locate the wakatime menu anywhere in the services section. I am unsure why.

**Comment by vanBassum** [comment]
It should be in Services/vanbassum/WakaTime

**Comment by Keelan-Matthews** [comment]
> It should be in Services/vanbassum/WakaTime

Indeed, however the services tab only shows options to enable ads etc for the project. "vanbassum" does not appear in "Services"

**Comment by vanBassum** [comment]
Strange, can you show me where you placed the folder with the extension?
I've added screenshots of my project. 

![image](https://github.com/vanBassum/Wakatime.Unity/assets/38683014/3e453ff7-3f92-48a5-ab26-63bfd59ab238)
![image](https://github.com/vanBassum/Wakatime.Unity/assets/38683014/b2212abb-11ea-4f8a-a7d3-d69a05d9ed93)

**Comment by Keelan-Matthews** [comment]
I installed the package through package manager>Add package via git url. I also don't seem to have the Services tab at all.
![image](https://github.com/vanBassum/Wakatime.Unity/assets/90719883/078d6e51-b3c4-4568-83a9-e24178766de0)
![image](https://github.com/vanBassum/Wakatime.Unity/assets/90719883/dabed1cf-ddf0-4ecd-bb48-6f839d9bf49b)

When I search for any instance of Services in Unity, this is all it gives me:
![image](https://github.com/vanBassum/Wakatime.Unity/assets/90719883/bdde88cd-4436-43fd-8f76-b13a3f293b1a)

**Comment by vanBassum** [comment]
Could you try changing the following line to something else? Maybe not in the service menu.

[Editor/UI/SettingsWindow.cs
](https://github.com/vanBassum/Wakatime.Unity/blob/2c0adecaf928ccfd7dcdf1988cb8e5b83e16f9e7/Editor/UI/SettingsWindow.cs#LL12C8-L12C50)

**Comment by vanBassum** [comment]
Steps I took to reproduce:
- Installed 2021.3.18f1
- Create project (3D unity build in renderer)
- Install the plugin (Window -> Package manager -> Add package from git url)

Now I get the following error: `Library\PackageCache\com.vanbassum.wakatime@2c0adecaf9\Editor\Plugin.cs(2,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)`

It seems newtonsoft JSON is missing.

I removed the reference to newtonsoft JSON since its not used anyway.

Now the plugin is initializing and the menu item appears.
