### ISSUE TITLE
Every heartbeat opens a 'Windows Terminal' window for a brief moment

### ISSUE THREAD

**Issue by buger404** [vanBassum/Wakatime.Unity#8]
The issue appears again on Windows 11, plugin version 0.1.0.
Every heartbeat opens a 'Windows Terminal' window for a brief moment.
Same as #5 I think

**Comment by vanBassum** [comment]
I don't own a Windows 11 pc personally, so reproducing this issue might be challenging. Although I suspect it's related to #5 like you say. I'll try to get my hands on a Windows 11 machine and look into this problem.

It might be best to use a git package that is natively supported by .net instead of running a process in the background.

**Comment by buger404** [comment]
Thank you for taking a look! Hope this wouldn't bother you too much :)

**Comment by vanBassum** [comment]
I did get my hands on a Windows 11 pc although I wasn't able to reproduce this problem.
Just to see if GIT is the source of the problem I added an option that allows you to disable GIT. Would you mind giving this a try?

**Comment by buger404** [comment]
I had a try just now.
The problem was solved after disable GIT.

**Comment by buger404** [comment]
I tried to read the codes and found a solution #9.

**Comment by vanBassum** [comment]
I've merged your pull request. Thanks for the effort

**Comment by ExerciseBook** [comment]
hint: `cat .git/HEAD`

**Comment by buger404** [comment]
> hint: `cat .git/HEAD`

wait a second, I'd like to try this way, I'll create a new pull request later.

**Comment by buger404** [comment]
I've open a new pull request #10 which tries https://github.com/vanBassum/Wakatime.Unity/issues/8#issuecomment-1407638459
